name: denalinodal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - obspy
  - jupyterlab
  - numpy
  - matplotlib
  - cartopy
  - scipy
  - tqdm
  - pygmt
  - geopandas
  - mpmath 
  - sympy
  - ipywidgets
  - jupyterlab_widgets
  - fiona
  - pysep
  - imageio.v2


